CREATE TYPE category AS ENUM(
    'Tea',
    'Pills',
    'Counseling',
    'Plant-based',
    'Body-care',
    'Recipes'
);

CREATE TABLE holistic_users_inventory(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES holistic_users(id),
    service_name TEXT NOT NULL,
    price NUMERIC (9, 2) NOT NULL,
    remaining_inventory INTEGER NOT NULL,
    description TEXT NOT NULL,
    product_category category NOT NULL,
    images TEXT
);